export const SITE_CONFIG = {
  name: "Ananth A",
  title: "Ananth A | Senior QA Automation Engineer | Playwright | Selenium | SDET",
  description:
    "Senior QA Automation Engineer specializing in Playwright, Selenium, API Testing, Performance Testing, and Software Quality. Explore projects, technical blogs, automation frameworks, and engineering experience.",
  url: "https://ananth-portfolio-xi.vercel.app",
  ogImage: "https://ananth-portfolio-xi.vercel.app/og-image.png",
  author: {
    name: "Ananth A",
    role: "Senior QA Automation Engineer / SDET",
    url: "https://ananth-portfolio-xi.vercel.app",
    email: "ananthalagarsamy@gmail.com",
    github: "https://github.com/Ananth-QA",
    linkedin: "https://www.linkedin.com/in/ananthalagarsamy",
    medium: "https://medium.com/@ananthalagarsamy",
  },
  primaryKeyword: "Automation QA Engineer",
  secondaryKeywords: [
    "Senior QA Engineer",
    "SDET",
    "Playwright Automation",
    "Selenium Automation",
    "Software Test Engineer",
    "QA Automation",
    "Automation Testing",
    "API Testing",
    "Performance Testing",
    "Test Automation",
    "Java Selenium",
    "Playwright Testing",
    "Manual Testing",
    "Software Quality",
  ],
  themeColor: "#020617",
  locale: "en_US",
};
